#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {recommendRelease} from './release-policy.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const base={name:'@tiinex/playthings',version:'1.2.3',type:'module',engines:{node:'>=22.16.0'},exports:{'.':'./index.mjs'},files:['src/**/*.mjs']};
let r=recommendRelease({currentVersion:'0.1.0-dev.0',currentPackage:{...base,version:'0.1.0-dev.0'}});
assert.equal(r.bump,'bootstrap');assert.equal(r.targetVersion,'0.1.0');
r=recommendRelease({currentVersion:'1.2.3',previousVersion:'1.2.3',previousPackage:base,currentPackage:base,commitMessages:['fix: repair edge case']});
assert.equal(r.bump,'patch');assert.equal(r.targetVersion,'1.2.4');
r=recommendRelease({currentVersion:'1.2.3',previousVersion:'1.2.3',previousPackage:base,currentPackage:base,commitMessages:['feat: add scene hook']});
assert.equal(r.bump,'minor');assert.equal(r.targetVersion,'1.3.0');
r=recommendRelease({currentVersion:'1.2.3',previousVersion:'1.2.3',previousPackage:base,currentPackage:{...base,exports:{...base.exports,'./scene':'./scene.mjs'}},commitMessages:[]});
assert.equal(r.bump,'minor');
r=recommendRelease({currentVersion:'1.2.3',previousVersion:'1.2.3',previousPackage:{...base,exports:{...base.exports,'./old':'./old.mjs'}},currentPackage:base,commitMessages:[]});
assert.equal(r.bump,'major');assert.equal(r.targetVersion,'2.0.0');
const zero={...base,version:'0.4.2'};
r=recommendRelease({currentVersion:'0.4.2',previousVersion:'0.4.2',previousPackage:{...zero,exports:{...zero.exports,'./old':'./old.mjs'}},currentPackage:zero,commitMessages:[]});
assert.equal(r.rawSeverity,'major');assert.equal(r.bump,'minor');assert.equal(r.targetVersion,'0.5.0');
r=recommendRelease({currentVersion:'0.4.2',previousVersion:'0.4.2',previousPackage:zero,currentPackage:zero,commitMessages:['chore: redesign\n\n[release:major]']});
assert.equal(r.bump,'major');assert.equal(r.targetVersion,'1.0.0');
const workflow=await fs.readFile(path.join(root,'.github/workflows/publish.yml'),'utf8');
for(const required of ['branches: [master]',"github.ref == 'refs/heads/master'",'id-token: write','environment: npm','npm run check','node tools/release.mjs prepare','node tools/release.mjs publish']) assert.ok(workflow.includes(required),`workflow missing ${required}`);
assert.ok(!workflow.includes('NPM_TOKEN')&&!workflow.includes('secrets.'));
assert.ok(!workflow.includes('types: [published]'));
const pkg=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));
assert.equal(pkg.scripts.release,'node tools/release.mjs preview');
assert.equal(pkg.scripts['publish:bootstrap'],'node tools/release.mjs bootstrap');
const guard=spawnSync(process.execPath,['tools/playthings/publish-guard.mjs'],{cwd:root,encoding:'utf8'});
assert.notEqual(guard.status,0);assert.match(guard.stderr,/Direct lifecycle publication is disabled/);
console.log(JSON.stringify({status:'pass',policyCases:7,workflow:'master-only',longLivedPublishSecret:false}));
