#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {recommendRelease} from './release-policy.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const base={name:'@tiinex/playthings',version:'1.2.3',type:'module',engines:{node:'>=22.16.0'},exports:{'.':'./index.mjs'},files:['src/**/*.mjs']};
let r=recommendRelease({currentVersion:'0.1.0-dev.0',currentPackage:{...base,version:'0.1.0-dev.0'}});
assert.equal(r.bump,'bootstrap');assert.equal(r.targetVersion,'0.1.0');
r=recommendRelease({currentVersion:'1.2.3',previousVersion:'1.2.3',previousPackage:base,currentPackage:base,commitMessages:['fix: repair edge case']});
assert.equal(r.bump,'patch');assert.equal(r.targetVersion,'1.2.4');
r=recommendRelease({currentVersion:'1.2.3',previousVersion:'1.2.3',previousPackage:base,currentPackage:base,commitMessages:['feat: add scene hook']});
assert.equal(r.bump,'minor');assert.equal(r.targetVersion,'1.3.0');
r=recommendRelease({currentVersion:'1.2.3',previousVersion:'1.2.3',previousPackage:base,currentPackage:{...base,exports:{...base.exports,'./scene':'./scene.mjs'}},commitMessages:[]});
assert.equal(r.bump,'minor');
r=recommendRelease({currentVersion:'1.2.3',previousVersion:'1.2.3',previousPackage:{...base,exports:{...base.exports,'./old':'./old.mjs'}},currentPackage:base,commitMessages:[]});
assert.equal(r.bump,'major');assert.equal(r.targetVersion,'2.0.0');
const zero={...base,version:'0.4.2'};
r=recommendRelease({currentVersion:'0.4.2',previousVersion:'0.4.2',previousPackage:{...zero,exports:{...zero.exports,'./old':'./old.mjs'}},currentPackage:zero,commitMessages:[]});
assert.equal(r.rawSeverity,'major');assert.equal(r.bump,'minor');assert.equal(r.targetVersion,'0.5.0');
r=recommendRelease({currentVersion:'0.4.2',previousVersion:'0.4.2',previousPackage:zero,currentPackage:zero,commitMessages:['chore: redesign\n\n[release:major]']});
assert.equal(r.bump,'major');assert.equal(r.targetVersion,'1.0.0');
const workflow=await fs.readFile(path.join(root,'.github/workflows/publish.yml'),'utf8');
for (const required of ['release:','types: [published]','id-token: write','contents: read','environment: npm','actions/checkout@v7','actions/setup-node@v7',"node-version: '24'",'npm ci --ignore-scripts','npm publish --access public','PLAYTHINGS_RELEASE_TAG']) assert.ok(workflow.includes(required),`workflow missing ${required}`);
assert.ok(!workflow.includes('NPM_TOKEN')&&!workflow.includes('secrets.'),'publish workflow must not depend on long-lived write secrets');
const tasks=JSON.parse(await fs.readFile(path.join(root,'.vscode/tasks.json'),'utf8'));
assert.ok(tasks.tasks.some(task=>task.label==='Tiinex: release @tiinex/playthings (auto)' && /npm run release/.test(task.command)));
const pkg=JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));
assert.equal(pkg.private,false);assert.equal(pkg.publishConfig.access,'public');assert.equal(pkg.publishConfig.registry,'https://registry.npmjs.org/');
assert.equal(pkg.scripts.release,'node tools/playthings/release.mjs');
assert.equal(pkg.scripts['publish:bootstrap'],'node tools/playthings/bootstrap-publish.mjs');
const help=spawnSync(process.execPath,['tools/playthings/release.mjs','--help'],{cwd:root,encoding:'utf8'});
assert.equal(help.status,0);assert.match(help.stdout,/Before 1\.0/i);
const guard=spawnSync(process.execPath,['tools/playthings/publish-guard.mjs'],{cwd:root,encoding:'utf8'});
assert.notEqual(guard.status,0);assert.match(guard.stderr,/only allowed from the GitHub Release workflow/i);
const bootstrapGuard=spawnSync(process.execPath,['tools/playthings/publish-guard.mjs'],{cwd:root,encoding:'utf8',env:{...process.env,PLAYTHINGS_BOOTSTRAP_PUBLISH:'1'}});
assert.equal(bootstrapGuard.status,0);
console.log(JSON.stringify({status:'pass',policyCases:7,workflow:'publish.yml',longLivedPublishSecret:false,vscodeReleaseTask:true,publishGuard:true}));
